:<<"END"
cp results/COLO829TB_BLCOV1_Shared_SBS96/Assignment_Solution/Activities/Assignment_Solution_Activity_Plots.pdf /mmfs1/gscratch/stergachislab/mhsohny/Tools/VCF2SPECTRUM/toscp/COLO829TB_BLCOV1_Shared_SBS96_Assignment_Solution_Activity_Plots.pdf
cp results/COLO829TB_BLCOV2_Shared_SBS96/Assignment_Solution/Activities/Assignment_Solution_Activity_Plots.pdf /mmfs1/gscratch/stergachislab/mhsohny/Tools/VCF2SPECTRUM/toscp/COLO829TB_BLCOV2_Shared_SBS96_Assignment_Solution_Activity_Plots.pdf
cp results/COLO829TB_BLCOV3_Shared_SBS96/Assignment_Solution/Activities/Assignment_Solution_Activity_Plots.pdf /mmfs1/gscratch/stergachislab/mhsohny/Tools/VCF2SPECTRUM/toscp/COLO829TB_BLCOV3_Shared_SBS96_Assignment_Solution_Activity_Plots.pdf
cp results/COLO829TB_BLCOV4_Shared_SBS96/Assignment_Solution/Activities/Assignment_Solution_Activity_Plots.pdf /mmfs1/gscratch/stergachislab/mhsohny/Tools/VCF2SPECTRUM/toscp/COLO829TB_BLCOV4_Shared_SBS96_Assignment_Solution_Activity_Plots.pdf
END
cp /mmfs1/gscratch/stergachislab/mhsohny/Tools/VCF2SPECTRUM/results/COLO829TB_Shared_SBS96/Assignment_Solution/Activities/Assignment_Solution_Activity_Plots.pdf ./toscp/COLO829TB_Truthset_SNV_Assignment_Solution_Activity_Plots.pdf
