[project]
authors = ["Min-Hwan 'Sohny' Sohn <mhsohny@uw.edu>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "SmkTemplate"
platforms = ["osx-64", "linux-64"]
version = "0.0.1"

[tasks]
fmt = "ruff format . && taplo format pixi.toml && snakefmt workflow/"
test = { cmd = [
  "snakemake",
  # once established you can add more arguments with your test data here
] }
snakemake = { cmd = "cd $INIT_CWD && snakemake -s $PIXI_PROJECT_ROOT/workflow/Snakefile" }


[dependencies]
conda = "*"
snakemake = "==8.21"
snakefmt = "*"
ruff = "*"
taplo = "*"
snakemake-executor-plugin-slurm = "*"
mutyper = "*"
python = ">=3.10"
pandas = "*"
matplotlib = "*"
seaborn = "*"
sigprofilermatrixgenerator = "*"
sigprofilerplotting = "*"
sigprofilerassignment = "*"
