# mhsohny
# For SBS96 signatures, the suffix of the sample should be _SBS96 and for ID83 should be _ID83

samples:
  COLO829TB_Shared_SBS96:
    vcf: "/mmfs1/gscratch/stergachislab/mhsohny/SMaHT/Improving_SomaticVariantCalling_through_DSA/Fiber-seq/VariantCalls_DeepVariant_1.6.1/Mutational_Spectrum/COLO829T_PassageB_DSA.deepvariant.PASS.snv.annot.shared.final.vcf.gz"
    signatures: ["SBS96"]
  COLO829TB_B-Specific_SBS96:
    vcf: "/mmfs1/gscratch/stergachislab/mhsohny/SMaHT/Improving_SomaticVariantCalling_through_DSA/Fiber-seq/VariantCalls_DeepVariant_1.6.1/Mutational_Spectrum/COLO829T_PassageB_DSA.deepvariant.PASS.snv.annot.b-specific.final.vcf.gz"
    signatures: ["SBS96"]
  COLO829TB_Truth_ID83:
    vcf: "/mmfs1/gscratch/stergachislab/mhsohny/SMaHT/Improving_SomaticVariantCalling_through_DSA/Fiber-seq/VariantCalls_DeepVariant_1.8.0/03.ID/Combined_total/COLO829T_Truthset-indels.vcf.gz"
    signatures: ["ID83"]

reference_genome: "/mmfs1/gscratch/stergachislab/assemblies/DSA_COLO829BL_v3.0.0.fasta"

#signature_analysis:
#  contexts: ["SBS96", "DBS78", "ID83"]
#  method: "SigProfilerExtractor"
#  min_mutations: 50

output_dir: "results"
